### ISSUE TITLE
Question about ActiveRecord model use in example

### ISSUE THREAD

**Issue by reedlaw** [zilverline/sequent-examples#11]
I have a question about this:
https://github.com/zilverline/sequent-examples/blob/45cb422616857654e2f8654dae5b79956e46df4a/rails-blog/app/controllers/articles_controller.rb#L20-L31
Validation is handled in the ActiveRecord model, Article. But in real usage, wouldn't it be handled in the AggregateRoot? Also, is it necessary to have an ActiveRecord model when PostRecord contains a projection from the AggregateRoot?

**Comment by reedlaw** [comment]
If I add validations in the command it works but it raises an exception. Is that supposed to be rescued in the controller?

**Comment by lvonk** [comment]
Hi @reedlaw 

> Validation is handled in the ActiveRecord model

In Sequent it should not be. Validation is handled in the [Commands](https://www.sequent.io/docs/concepts/validations.html). It uses ActiveModel validations from Rails.

The `PostRecord` is an ActiveRecord model, so there is no need to add one extra. See:

https://github.com/zilverline/sequent-examples/blob/45cb422616857654e2f8654dae5b79956e46df4a/rails-blog/app/sequent/records/post_record.rb#L1-L2

> Is that supposed to be rescued in the controller?

Yes. The `CommandNotValid` error contains the failed command and has some convenience methods to access the errors. If you want direct access your self you will (for now) need to open the class and access the `@command` which is just an ActiveModel object (containing the `Errors` object).

Hope this helps

**Comment by reedlaw** [comment]
In that case this example app is a bit misleading, wouldn't you say? Are you open to PRs? I've already made some changes locally to make it align better with the docs.

**Comment by lvonk** [comment]
Yes all improvements are welcome. Purpose of this example is how you can use Sequent in a Rails application. So therefor the distinction between a Rails model like `Article`  and a Sequent projection like `PostRecord` is intentional.
But I fully agree the example app is a bit minimal and could be improved. What are you suggesting?

**Comment by reedlaw** [comment]
I opened a PR with my changes. I'm not sure what to do with the `new` action but I guess we can just do things in a non-Rails way. That is, just POST some params and validate, rescuing the exception if there's an error and rendering a page with errors.

**Comment by lvonk** [comment]
The new action typically returns an empty @command object (maybe prefilled with some default values). So if you have a form that creates the `Post` the new action could be something like:

```ruby
  def new
    @command = AddPost.new(language: DEFAULT_LANGUAGE)
  end
```

You can then use that `@command` object to bind to your form. Although I do think the Rails form binding only works well with ActiveRecord and not with ActiveModel last time I checked.
